name: CI
on:
  - push
env:
  PACKAGE_DIRECTORY: "."
  JAVA_VERSION: "20"
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v2

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install dependencies
        shell: cmd
        run: |
          cd %PACKAGE_DIRECTORY%
          mvn install -DskipTests=true -B -V
          cd ..

      - name: Run Tests
        shell: cmd
        run: |
          cd %PACKAGE_DIRECTORY%
          mvn -B test
          cd ..
      
